### ISSUE TITLE
[Django + Python] Generic view failure wrapper

### ISSUE THREAD

**Issue by vcai122** [pennlabs/penn-mobile#204]
For error handling, a lot of our views need try-excepted similar to: https://github.com/pennlabs/penn-mobile/pull/198/files/5e419b8b39050c0852ae941541f0e71be449356f, so that we can return the appropriate response. 

To not have to re-write this code everywhere, a helper wrapper function/decorator could be useful.

**Comment by PavankumarUppar** [comment]
@vcai122 I'm interested in working on this! Please assign this job to me.
